package cn.qiniu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class LiveVideoTerrorCuts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.job_id
     *
     * @mbggenerated
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.timestamp
     *
     * @mbggenerated
     */
    private String timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.reqid
     *
     * @mbggenerated
     */
    private String reqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.del_flg
     *
     * @mbggenerated
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.review_type
     *
     * @mbggenerated
     */
    private String reviewType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live_video_terror_cuts.score
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_terror_cuts
     *
     * @mbggenerated
     */
    public LiveVideoTerrorCuts(String id, String jobId, String url, String timestamp, String reqid, String label, String createdBy, Date createdAt, String updatedBy, Date updatedAt, String delFlg, String reviewType, BigDecimal score) {
        this.id = id;
        this.jobId = jobId;
        this.url = url;
        this.timestamp = timestamp;
        this.reqid = reqid;
        this.label = label;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
        this.delFlg = delFlg;
        this.reviewType = reviewType;
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_video_terror_cuts
     *
     * @mbggenerated
     */
    public LiveVideoTerrorCuts() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.id
     *
     * @return the value of live_video_terror_cuts.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.id
     *
     * @param id the value for live_video_terror_cuts.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.job_id
     *
     * @return the value of live_video_terror_cuts.job_id
     *
     * @mbggenerated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.job_id
     *
     * @param jobId the value for live_video_terror_cuts.job_id
     *
     * @mbggenerated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.url
     *
     * @return the value of live_video_terror_cuts.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.url
     *
     * @param url the value for live_video_terror_cuts.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.timestamp
     *
     * @return the value of live_video_terror_cuts.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.timestamp
     *
     * @param timestamp the value for live_video_terror_cuts.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.reqid
     *
     * @return the value of live_video_terror_cuts.reqid
     *
     * @mbggenerated
     */
    public String getReqid() {
        return reqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.reqid
     *
     * @param reqid the value for live_video_terror_cuts.reqid
     *
     * @mbggenerated
     */
    public void setReqid(String reqid) {
        this.reqid = reqid == null ? null : reqid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.label
     *
     * @return the value of live_video_terror_cuts.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.label
     *
     * @param label the value for live_video_terror_cuts.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.created_by
     *
     * @return the value of live_video_terror_cuts.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.created_by
     *
     * @param createdBy the value for live_video_terror_cuts.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.created_at
     *
     * @return the value of live_video_terror_cuts.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.created_at
     *
     * @param createdAt the value for live_video_terror_cuts.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.updated_by
     *
     * @return the value of live_video_terror_cuts.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.updated_by
     *
     * @param updatedBy the value for live_video_terror_cuts.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.updated_at
     *
     * @return the value of live_video_terror_cuts.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.updated_at
     *
     * @param updatedAt the value for live_video_terror_cuts.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.del_flg
     *
     * @return the value of live_video_terror_cuts.del_flg
     *
     * @mbggenerated
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.del_flg
     *
     * @param delFlg the value for live_video_terror_cuts.del_flg
     *
     * @mbggenerated
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.review_type
     *
     * @return the value of live_video_terror_cuts.review_type
     *
     * @mbggenerated
     */
    public String getReviewType() {
        return reviewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.review_type
     *
     * @param reviewType the value for live_video_terror_cuts.review_type
     *
     * @mbggenerated
     */
    public void setReviewType(String reviewType) {
        this.reviewType = reviewType == null ? null : reviewType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live_video_terror_cuts.score
     *
     * @return the value of live_video_terror_cuts.score
     *
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live_video_terror_cuts.score
     *
     * @param score the value for live_video_terror_cuts.score
     *
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }
}