package cn.qiniu.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReviewVideoInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public ReviewVideoInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("`video_id` is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("`video_id` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(String value) {
            addCriterion("`video_id` =", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(String value) {
            addCriterion("`video_id` <>", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(String value) {
            addCriterion("`video_id` >", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(String value) {
            addCriterion("`video_id` >=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(String value) {
            addCriterion("`video_id` <", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(String value) {
            addCriterion("`video_id` <=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLike(String value) {
            addCriterion("`video_id` like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotLike(String value) {
            addCriterion("`video_id` not like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<String> values) {
            addCriterion("`video_id` in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<String> values) {
            addCriterion("`video_id` not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(String value1, String value2) {
            addCriterion("`video_id` between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(String value1, String value2) {
            addCriterion("`video_id` not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoUriIsNull() {
            addCriterion("`video_uri` is null");
            return (Criteria) this;
        }

        public Criteria andVideoUriIsNotNull() {
            addCriterion("`video_uri` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUriEqualTo(String value) {
            addCriterion("`video_uri` =", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotEqualTo(String value) {
            addCriterion("`video_uri` <>", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriGreaterThan(String value) {
            addCriterion("`video_uri` >", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriGreaterThanOrEqualTo(String value) {
            addCriterion("`video_uri` >=", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriLessThan(String value) {
            addCriterion("`video_uri` <", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriLessThanOrEqualTo(String value) {
            addCriterion("`video_uri` <=", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriLike(String value) {
            addCriterion("`video_uri` like", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotLike(String value) {
            addCriterion("`video_uri` not like", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriIn(List<String> values) {
            addCriterion("`video_uri` in", values, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotIn(List<String> values) {
            addCriterion("`video_uri` not in", values, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriBetween(String value1, String value2) {
            addCriterion("`video_uri` between", value1, value2, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotBetween(String value1, String value2) {
            addCriterion("`video_uri` not between", value1, value2, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoDescIsNull() {
            addCriterion("`video_desc` is null");
            return (Criteria) this;
        }

        public Criteria andVideoDescIsNotNull() {
            addCriterion("`video_desc` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoDescEqualTo(String value) {
            addCriterion("`video_desc` =", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescNotEqualTo(String value) {
            addCriterion("`video_desc` <>", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescGreaterThan(String value) {
            addCriterion("`video_desc` >", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescGreaterThanOrEqualTo(String value) {
            addCriterion("`video_desc` >=", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescLessThan(String value) {
            addCriterion("`video_desc` <", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescLessThanOrEqualTo(String value) {
            addCriterion("`video_desc` <=", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescLike(String value) {
            addCriterion("`video_desc` like", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescNotLike(String value) {
            addCriterion("`video_desc` not like", value, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescIn(List<String> values) {
            addCriterion("`video_desc` in", values, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescNotIn(List<String> values) {
            addCriterion("`video_desc` not in", values, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescBetween(String value1, String value2) {
            addCriterion("`video_desc` between", value1, value2, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoDescNotBetween(String value1, String value2) {
            addCriterion("`video_desc` not between", value1, value2, "videoDesc");
            return (Criteria) this;
        }

        public Criteria andVideoMetaIsNull() {
            addCriterion("`video_meta` is null");
            return (Criteria) this;
        }

        public Criteria andVideoMetaIsNotNull() {
            addCriterion("`video_meta` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoMetaEqualTo(String value) {
            addCriterion("`video_meta` =", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaNotEqualTo(String value) {
            addCriterion("`video_meta` <>", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaGreaterThan(String value) {
            addCriterion("`video_meta` >", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaGreaterThanOrEqualTo(String value) {
            addCriterion("`video_meta` >=", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaLessThan(String value) {
            addCriterion("`video_meta` <", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaLessThanOrEqualTo(String value) {
            addCriterion("`video_meta` <=", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaLike(String value) {
            addCriterion("`video_meta` like", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaNotLike(String value) {
            addCriterion("`video_meta` not like", value, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaIn(List<String> values) {
            addCriterion("`video_meta` in", values, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaNotIn(List<String> values) {
            addCriterion("`video_meta` not in", values, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaBetween(String value1, String value2) {
            addCriterion("`video_meta` between", value1, value2, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andVideoMetaNotBetween(String value1, String value2) {
            addCriterion("`video_meta` not between", value1, value2, "videoMeta");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgIsNull() {
            addCriterion("`stop_review_flg` is null");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgIsNotNull() {
            addCriterion("`stop_review_flg` is not null");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgEqualTo(String value) {
            addCriterion("`stop_review_flg` =", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgNotEqualTo(String value) {
            addCriterion("`stop_review_flg` <>", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgGreaterThan(String value) {
            addCriterion("`stop_review_flg` >", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgGreaterThanOrEqualTo(String value) {
            addCriterion("`stop_review_flg` >=", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgLessThan(String value) {
            addCriterion("`stop_review_flg` <", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgLessThanOrEqualTo(String value) {
            addCriterion("`stop_review_flg` <=", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgLike(String value) {
            addCriterion("`stop_review_flg` like", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgNotLike(String value) {
            addCriterion("`stop_review_flg` not like", value, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgIn(List<String> values) {
            addCriterion("`stop_review_flg` in", values, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgNotIn(List<String> values) {
            addCriterion("`stop_review_flg` not in", values, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgBetween(String value1, String value2) {
            addCriterion("`stop_review_flg` between", value1, value2, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andStopReviewFlgNotBetween(String value1, String value2) {
            addCriterion("`stop_review_flg` not between", value1, value2, "stopReviewFlg");
            return (Criteria) this;
        }

        public Criteria andWaitIsNull() {
            addCriterion("`wait` is null");
            return (Criteria) this;
        }

        public Criteria andWaitIsNotNull() {
            addCriterion("`wait` is not null");
            return (Criteria) this;
        }

        public Criteria andWaitEqualTo(Boolean value) {
            addCriterion("`wait` =", value, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitNotEqualTo(Boolean value) {
            addCriterion("`wait` <>", value, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitGreaterThan(Boolean value) {
            addCriterion("`wait` >", value, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`wait` >=", value, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitLessThan(Boolean value) {
            addCriterion("`wait` <", value, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitLessThanOrEqualTo(Boolean value) {
            addCriterion("`wait` <=", value, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitIn(List<Boolean> values) {
            addCriterion("`wait` in", values, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitNotIn(List<Boolean> values) {
            addCriterion("`wait` not in", values, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitBetween(Boolean value1, Boolean value2) {
            addCriterion("`wait` between", value1, value2, "wait");
            return (Criteria) this;
        }

        public Criteria andWaitNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`wait` not between", value1, value2, "wait");
            return (Criteria) this;
        }

        public Criteria andReviewTypeIsNull() {
            addCriterion("`review_type` is null");
            return (Criteria) this;
        }

        public Criteria andReviewTypeIsNotNull() {
            addCriterion("`review_type` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewTypeEqualTo(String value) {
            addCriterion("`review_type` =", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeNotEqualTo(String value) {
            addCriterion("`review_type` <>", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeGreaterThan(String value) {
            addCriterion("`review_type` >", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`review_type` >=", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeLessThan(String value) {
            addCriterion("`review_type` <", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeLessThanOrEqualTo(String value) {
            addCriterion("`review_type` <=", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeLike(String value) {
            addCriterion("`review_type` like", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeNotLike(String value) {
            addCriterion("`review_type` not like", value, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeIn(List<String> values) {
            addCriterion("`review_type` in", values, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeNotIn(List<String> values) {
            addCriterion("`review_type` not in", values, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeBetween(String value1, String value2) {
            addCriterion("`review_type` between", value1, value2, "reviewType");
            return (Criteria) this;
        }

        public Criteria andReviewTypeNotBetween(String value1, String value2) {
            addCriterion("`review_type` not between", value1, value2, "reviewType");
            return (Criteria) this;
        }

        public Criteria andVideoSaveIsNull() {
            addCriterion("`video_save` is null");
            return (Criteria) this;
        }

        public Criteria andVideoSaveIsNotNull() {
            addCriterion("`video_save` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoSaveEqualTo(String value) {
            addCriterion("`video_save` =", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveNotEqualTo(String value) {
            addCriterion("`video_save` <>", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveGreaterThan(String value) {
            addCriterion("`video_save` >", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveGreaterThanOrEqualTo(String value) {
            addCriterion("`video_save` >=", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveLessThan(String value) {
            addCriterion("`video_save` <", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveLessThanOrEqualTo(String value) {
            addCriterion("`video_save` <=", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveLike(String value) {
            addCriterion("`video_save` like", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveNotLike(String value) {
            addCriterion("`video_save` not like", value, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveIn(List<String> values) {
            addCriterion("`video_save` in", values, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveNotIn(List<String> values) {
            addCriterion("`video_save` not in", values, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveBetween(String value1, String value2) {
            addCriterion("`video_save` between", value1, value2, "videoSave");
            return (Criteria) this;
        }

        public Criteria andVideoSaveNotBetween(String value1, String value2) {
            addCriterion("`video_save` not between", value1, value2, "videoSave");
            return (Criteria) this;
        }

        public Criteria andHookHostIsNull() {
            addCriterion("`hook_host` is null");
            return (Criteria) this;
        }

        public Criteria andHookHostIsNotNull() {
            addCriterion("`hook_host` is not null");
            return (Criteria) this;
        }

        public Criteria andHookHostEqualTo(String value) {
            addCriterion("`hook_host` =", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostNotEqualTo(String value) {
            addCriterion("`hook_host` <>", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostGreaterThan(String value) {
            addCriterion("`hook_host` >", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostGreaterThanOrEqualTo(String value) {
            addCriterion("`hook_host` >=", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostLessThan(String value) {
            addCriterion("`hook_host` <", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostLessThanOrEqualTo(String value) {
            addCriterion("`hook_host` <=", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostLike(String value) {
            addCriterion("`hook_host` like", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostNotLike(String value) {
            addCriterion("`hook_host` not like", value, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostIn(List<String> values) {
            addCriterion("`hook_host` in", values, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostNotIn(List<String> values) {
            addCriterion("`hook_host` not in", values, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostBetween(String value1, String value2) {
            addCriterion("`hook_host` between", value1, value2, "hookHost");
            return (Criteria) this;
        }

        public Criteria andHookHostNotBetween(String value1, String value2) {
            addCriterion("`hook_host` not between", value1, value2, "hookHost");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("`created_by` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("`created_by` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("`created_by` =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("`created_by` <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("`created_by` >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("`created_by` >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("`created_by` <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("`created_by` <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("`created_by` like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("`created_by` not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("`created_by` in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("`created_by` not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("`created_by` between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("`created_by` not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("`created_at` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("`created_at` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("`created_at` =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("`created_at` <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("`created_at` >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_at` >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("`created_at` <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`created_at` <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("`created_at` in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("`created_at` not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("`created_at` between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`created_at` not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("`updated_by` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("`updated_by` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("`updated_by` =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("`updated_by` <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("`updated_by` >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("`updated_by` >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("`updated_by` <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("`updated_by` <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("`updated_by` like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("`updated_by` not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("`updated_by` in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("`updated_by` not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("`updated_by` between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("`updated_by` not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("`updated_at` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("`updated_at` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("`updated_at` =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("`updated_at` <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("`updated_at` >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_at` >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("`updated_at` <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`updated_at` <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("`updated_at` in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("`updated_at` not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("`updated_at` between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`updated_at` not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDelFlgIsNull() {
            addCriterion("`del_flg` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlgIsNotNull() {
            addCriterion("`del_flg` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlgEqualTo(String value) {
            addCriterion("`del_flg` =", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotEqualTo(String value) {
            addCriterion("`del_flg` <>", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgGreaterThan(String value) {
            addCriterion("`del_flg` >", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("`del_flg` >=", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLessThan(String value) {
            addCriterion("`del_flg` <", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLessThanOrEqualTo(String value) {
            addCriterion("`del_flg` <=", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLike(String value) {
            addCriterion("`del_flg` like", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotLike(String value) {
            addCriterion("`del_flg` not like", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgIn(List<String> values) {
            addCriterion("`del_flg` in", values, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotIn(List<String> values) {
            addCriterion("`del_flg` not in", values, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgBetween(String value1, String value2) {
            addCriterion("`del_flg` between", value1, value2, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotBetween(String value1, String value2) {
            addCriterion("`del_flg` not between", value1, value2, "delFlg");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNull() {
            addCriterion("`video_type` is null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNotNull() {
            addCriterion("`video_type` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeEqualTo(String value) {
            addCriterion("`video_type` =", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotEqualTo(String value) {
            addCriterion("`video_type` <>", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThan(String value) {
            addCriterion("`video_type` >", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`video_type` >=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThan(String value) {
            addCriterion("`video_type` <", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThanOrEqualTo(String value) {
            addCriterion("`video_type` <=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLike(String value) {
            addCriterion("`video_type` like", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotLike(String value) {
            addCriterion("`video_type` not like", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIn(List<String> values) {
            addCriterion("`video_type` in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotIn(List<String> values) {
            addCriterion("`video_type` not in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeBetween(String value1, String value2) {
            addCriterion("`video_type` between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotBetween(String value1, String value2) {
            addCriterion("`video_type` not between", value1, value2, "videoType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_information
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}