package cn.qiniu.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReviewVideoManagerSegmentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public ReviewVideoManagerSegmentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("`video_id` is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("`video_id` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(String value) {
            addCriterion("`video_id` =", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(String value) {
            addCriterion("`video_id` <>", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(String value) {
            addCriterion("`video_id` >", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(String value) {
            addCriterion("`video_id` >=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(String value) {
            addCriterion("`video_id` <", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(String value) {
            addCriterion("`video_id` <=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLike(String value) {
            addCriterion("`video_id` like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotLike(String value) {
            addCriterion("`video_id` not like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<String> values) {
            addCriterion("`video_id` in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<String> values) {
            addCriterion("`video_id` not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(String value1, String value2) {
            addCriterion("`video_id` between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(String value1, String value2) {
            addCriterion("`video_id` not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andOpIsNull() {
            addCriterion("`op` is null");
            return (Criteria) this;
        }

        public Criteria andOpIsNotNull() {
            addCriterion("`op` is not null");
            return (Criteria) this;
        }

        public Criteria andOpEqualTo(String value) {
            addCriterion("`op` =", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpNotEqualTo(String value) {
            addCriterion("`op` <>", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpGreaterThan(String value) {
            addCriterion("`op` >", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpGreaterThanOrEqualTo(String value) {
            addCriterion("`op` >=", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpLessThan(String value) {
            addCriterion("`op` <", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpLessThanOrEqualTo(String value) {
            addCriterion("`op` <=", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpLike(String value) {
            addCriterion("`op` like", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpNotLike(String value) {
            addCriterion("`op` not like", value, "op");
            return (Criteria) this;
        }

        public Criteria andOpIn(List<String> values) {
            addCriterion("`op` in", values, "op");
            return (Criteria) this;
        }

        public Criteria andOpNotIn(List<String> values) {
            addCriterion("`op` not in", values, "op");
            return (Criteria) this;
        }

        public Criteria andOpBetween(String value1, String value2) {
            addCriterion("`op` between", value1, value2, "op");
            return (Criteria) this;
        }

        public Criteria andOpNotBetween(String value1, String value2) {
            addCriterion("`op` not between", value1, value2, "op");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginIsNull() {
            addCriterion("`offset_begin` is null");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginIsNotNull() {
            addCriterion("`offset_begin` is not null");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginEqualTo(Integer value) {
            addCriterion("`offset_begin` =", value, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginNotEqualTo(Integer value) {
            addCriterion("`offset_begin` <>", value, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginGreaterThan(Integer value) {
            addCriterion("`offset_begin` >", value, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginGreaterThanOrEqualTo(Integer value) {
            addCriterion("`offset_begin` >=", value, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginLessThan(Integer value) {
            addCriterion("`offset_begin` <", value, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginLessThanOrEqualTo(Integer value) {
            addCriterion("`offset_begin` <=", value, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginIn(List<Integer> values) {
            addCriterion("`offset_begin` in", values, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginNotIn(List<Integer> values) {
            addCriterion("`offset_begin` not in", values, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginBetween(Integer value1, Integer value2) {
            addCriterion("`offset_begin` between", value1, value2, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetBeginNotBetween(Integer value1, Integer value2) {
            addCriterion("`offset_begin` not between", value1, value2, "offsetBegin");
            return (Criteria) this;
        }

        public Criteria andOffsetEndIsNull() {
            addCriterion("`offset_end` is null");
            return (Criteria) this;
        }

        public Criteria andOffsetEndIsNotNull() {
            addCriterion("`offset_end` is not null");
            return (Criteria) this;
        }

        public Criteria andOffsetEndEqualTo(Integer value) {
            addCriterion("`offset_end` =", value, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndNotEqualTo(Integer value) {
            addCriterion("`offset_end` <>", value, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndGreaterThan(Integer value) {
            addCriterion("`offset_end` >", value, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndGreaterThanOrEqualTo(Integer value) {
            addCriterion("`offset_end` >=", value, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndLessThan(Integer value) {
            addCriterion("`offset_end` <", value, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndLessThanOrEqualTo(Integer value) {
            addCriterion("`offset_end` <=", value, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndIn(List<Integer> values) {
            addCriterion("`offset_end` in", values, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndNotIn(List<Integer> values) {
            addCriterion("`offset_end` not in", values, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndBetween(Integer value1, Integer value2) {
            addCriterion("`offset_end` between", value1, value2, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andOffsetEndNotBetween(Integer value1, Integer value2) {
            addCriterion("`offset_end` not between", value1, value2, "offsetEnd");
            return (Criteria) this;
        }

        public Criteria andUriIsNull() {
            addCriterion("`uri` is null");
            return (Criteria) this;
        }

        public Criteria andUriIsNotNull() {
            addCriterion("`uri` is not null");
            return (Criteria) this;
        }

        public Criteria andUriEqualTo(String value) {
            addCriterion("`uri` =", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotEqualTo(String value) {
            addCriterion("`uri` <>", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriGreaterThan(String value) {
            addCriterion("`uri` >", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriGreaterThanOrEqualTo(String value) {
            addCriterion("`uri` >=", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriLessThan(String value) {
            addCriterion("`uri` <", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriLessThanOrEqualTo(String value) {
            addCriterion("`uri` <=", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriLike(String value) {
            addCriterion("`uri` like", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotLike(String value) {
            addCriterion("`uri` not like", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriIn(List<String> values) {
            addCriterion("`uri` in", values, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotIn(List<String> values) {
            addCriterion("`uri` not in", values, "uri");
            return (Criteria) this;
        }

        public Criteria andUriBetween(String value1, String value2) {
            addCriterion("`uri` between", value1, value2, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotBetween(String value1, String value2) {
            addCriterion("`uri` not between", value1, value2, "uri");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("`level` is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("`level` is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("`level` =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("`level` <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("`level` >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`level` >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("`level` <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("`level` <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("`level` like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("`level` not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("`level` in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("`level` not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("`level` between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("`level` not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andManualLevelIsNull() {
            addCriterion("`manual_level` is null");
            return (Criteria) this;
        }

        public Criteria andManualLevelIsNotNull() {
            addCriterion("`manual_level` is not null");
            return (Criteria) this;
        }

        public Criteria andManualLevelEqualTo(String value) {
            addCriterion("`manual_level` =", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelNotEqualTo(String value) {
            addCriterion("`manual_level` <>", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelGreaterThan(String value) {
            addCriterion("`manual_level` >", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`manual_level` >=", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelLessThan(String value) {
            addCriterion("`manual_level` <", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelLessThanOrEqualTo(String value) {
            addCriterion("`manual_level` <=", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelLike(String value) {
            addCriterion("`manual_level` like", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelNotLike(String value) {
            addCriterion("`manual_level` not like", value, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelIn(List<String> values) {
            addCriterion("`manual_level` in", values, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelNotIn(List<String> values) {
            addCriterion("`manual_level` not in", values, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelBetween(String value1, String value2) {
            addCriterion("`manual_level` between", value1, value2, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andManualLevelNotBetween(String value1, String value2) {
            addCriterion("`manual_level` not between", value1, value2, "manualLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelIsNull() {
            addCriterion("`robotic_level` is null");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelIsNotNull() {
            addCriterion("`robotic_level` is not null");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelEqualTo(String value) {
            addCriterion("`robotic_level` =", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelNotEqualTo(String value) {
            addCriterion("`robotic_level` <>", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelGreaterThan(String value) {
            addCriterion("`robotic_level` >", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`robotic_level` >=", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelLessThan(String value) {
            addCriterion("`robotic_level` <", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelLessThanOrEqualTo(String value) {
            addCriterion("`robotic_level` <=", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelLike(String value) {
            addCriterion("`robotic_level` like", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelNotLike(String value) {
            addCriterion("`robotic_level` not like", value, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelIn(List<String> values) {
            addCriterion("`robotic_level` in", values, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelNotIn(List<String> values) {
            addCriterion("`robotic_level` not in", values, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelBetween(String value1, String value2) {
            addCriterion("`robotic_level` between", value1, value2, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticLevelNotBetween(String value1, String value2) {
            addCriterion("`robotic_level` not between", value1, value2, "roboticLevel");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreIsNull() {
            addCriterion("`robotic_score` is null");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreIsNotNull() {
            addCriterion("`robotic_score` is not null");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreEqualTo(BigDecimal value) {
            addCriterion("`robotic_score` =", value, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreNotEqualTo(BigDecimal value) {
            addCriterion("`robotic_score` <>", value, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreGreaterThan(BigDecimal value) {
            addCriterion("`robotic_score` >", value, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`robotic_score` >=", value, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreLessThan(BigDecimal value) {
            addCriterion("`robotic_score` <", value, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`robotic_score` <=", value, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreIn(List<BigDecimal> values) {
            addCriterion("`robotic_score` in", values, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreNotIn(List<BigDecimal> values) {
            addCriterion("`robotic_score` not in", values, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`robotic_score` between", value1, value2, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andRoboticScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`robotic_score` not between", value1, value2, "roboticScore");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("`created_by` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("`created_by` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("`created_by` =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("`created_by` <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("`created_by` >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("`created_by` >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("`created_by` <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("`created_by` <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("`created_by` like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("`created_by` not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("`created_by` in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("`created_by` not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("`created_by` between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("`created_by` not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("`created_at` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("`created_at` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("`created_at` =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("`created_at` <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("`created_at` >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_at` >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("`created_at` <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`created_at` <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("`created_at` in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("`created_at` not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("`created_at` between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`created_at` not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("`updated_by` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("`updated_by` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("`updated_by` =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("`updated_by` <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("`updated_by` >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("`updated_by` >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("`updated_by` <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("`updated_by` <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("`updated_by` like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("`updated_by` not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("`updated_by` in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("`updated_by` not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("`updated_by` between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("`updated_by` not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("`updated_at` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("`updated_at` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("`updated_at` =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("`updated_at` <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("`updated_at` >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_at` >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("`updated_at` <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`updated_at` <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("`updated_at` in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("`updated_at` not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("`updated_at` between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`updated_at` not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDelFlgIsNull() {
            addCriterion("`del_flg` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlgIsNotNull() {
            addCriterion("`del_flg` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlgEqualTo(String value) {
            addCriterion("`del_flg` =", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotEqualTo(String value) {
            addCriterion("`del_flg` <>", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgGreaterThan(String value) {
            addCriterion("`del_flg` >", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("`del_flg` >=", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLessThan(String value) {
            addCriterion("`del_flg` <", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLessThanOrEqualTo(String value) {
            addCriterion("`del_flg` <=", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLike(String value) {
            addCriterion("`del_flg` like", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotLike(String value) {
            addCriterion("`del_flg` not like", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgIn(List<String> values) {
            addCriterion("`del_flg` in", values, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotIn(List<String> values) {
            addCriterion("`del_flg` not in", values, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgBetween(String value1, String value2) {
            addCriterion("`del_flg` between", value1, value2, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotBetween(String value1, String value2) {
            addCriterion("`del_flg` not between", value1, value2, "delFlg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}