package cn.qiniu.mapper;

import cn.qiniu.entity.ReviewLevelSetting;
import cn.qiniu.entity.ReviewLevelSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReviewLevelSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    int countByExample(ReviewLevelSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewLevelSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `review_level_setting`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `review_level_setting` (`id`, `ops_op`, ",
        "`ops_op_label`, `ops_op_level`, ",
        "`created_by`, `created_at`, ",
        "`updated_by`, `updated_at`, ",
        "`del_flg`)",
        "values (#{id,jdbcType=VARCHAR}, #{opsOp,jdbcType=VARCHAR}, ",
        "#{opsOpLabel,jdbcType=VARCHAR}, #{opsOpLevel,jdbcType=VARCHAR}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedBy,jdbcType=VARCHAR}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{delFlg,jdbcType=VARCHAR})"
    })
    int insert(ReviewLevelSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    int insertSelective(ReviewLevelSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    List<ReviewLevelSetting> selectByExample(ReviewLevelSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `ops_op`, `ops_op_label`, `ops_op_level`, `created_by`, `created_at`, ",
        "`updated_by`, `updated_at`, `del_flg`",
        "from `review_level_setting`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReviewLevelSetting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewLevelSetting record, @Param("example") ReviewLevelSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewLevelSetting record, @Param("example") ReviewLevelSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReviewLevelSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_level_setting
     *
     * @mbggenerated
     */
    @Update({
        "update `review_level_setting`",
        "set `ops_op` = #{opsOp,jdbcType=VARCHAR},",
          "`ops_op_label` = #{opsOpLabel,jdbcType=VARCHAR},",
          "`ops_op_level` = #{opsOpLevel,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReviewLevelSetting record);
}