package cn.qiniu.mapper;

import cn.qiniu.entity.ReviewVideoSegments;
import cn.qiniu.entity.ReviewVideoSegmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReviewVideoSegmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    int countByExample(ReviewVideoSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewVideoSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `review_video_segments`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `review_video_segments` (`id`, `job_id`, ",
        "`video_id`, `source`, ",
        "`video_uri`, `video_cover`, ",
        "`review_level`, `review_ops_pulp_level`, ",
        "`review_ops_terror_level`, `review_ops_politician_level`, ",
        "`review_segments_op`, `review_segments_offsetBegin`, ",
        "`review_segments_offsetEnd`, `review_segments_uri`, ",
        "`review_segments_cuts_offset`, `review_segments_cuts_uri`, ",
        "`review_segments_level`, `created_by`, ",
        "`created_at`, `updated_by`, ",
        "`updated_at`, `del_flg`)",
        "values (#{id,jdbcType=VARCHAR}, #{jobId,jdbcType=VARCHAR}, ",
        "#{videoId,jdbcType=VARCHAR}, #{source,jdbcType=VARCHAR}, ",
        "#{videoUri,jdbcType=VARCHAR}, #{videoCover,jdbcType=VARCHAR}, ",
        "#{reviewLevel,jdbcType=VARCHAR}, #{reviewOpsPulpLevel,jdbcType=VARCHAR}, ",
        "#{reviewOpsTerrorLevel,jdbcType=VARCHAR}, #{reviewOpsPoliticianLevel,jdbcType=VARCHAR}, ",
        "#{reviewSegmentsOp,jdbcType=VARCHAR}, #{reviewSegmentsOffsetbegin,jdbcType=INTEGER}, ",
        "#{reviewSegmentsOffsetend,jdbcType=INTEGER}, #{reviewSegmentsUri,jdbcType=VARCHAR}, ",
        "#{reviewSegmentsCutsOffset,jdbcType=INTEGER}, #{reviewSegmentsCutsUri,jdbcType=VARCHAR}, ",
        "#{reviewSegmentsLevel,jdbcType=VARCHAR}, #{createdBy,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedBy,jdbcType=VARCHAR}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{delFlg,jdbcType=VARCHAR})"
    })
    int insert(ReviewVideoSegments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    int insertSelective(ReviewVideoSegments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    List<ReviewVideoSegments> selectByExample(ReviewVideoSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `job_id`, `video_id`, `source`, `video_uri`, `video_cover`, `review_level`, ",
        "`review_ops_pulp_level`, `review_ops_terror_level`, `review_ops_politician_level`, ",
        "`review_segments_op`, `review_segments_offsetBegin`, `review_segments_offsetEnd`, ",
        "`review_segments_uri`, `review_segments_cuts_offset`, `review_segments_cuts_uri`, ",
        "`review_segments_level`, `created_by`, `created_at`, `updated_by`, `updated_at`, ",
        "`del_flg`",
        "from `review_video_segments`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReviewVideoSegments selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewVideoSegments record, @Param("example") ReviewVideoSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewVideoSegments record, @Param("example") ReviewVideoSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReviewVideoSegments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_segments
     *
     * @mbggenerated
     */
    @Update({
        "update `review_video_segments`",
        "set `job_id` = #{jobId,jdbcType=VARCHAR},",
          "`video_id` = #{videoId,jdbcType=VARCHAR},",
          "`source` = #{source,jdbcType=VARCHAR},",
          "`video_uri` = #{videoUri,jdbcType=VARCHAR},",
          "`video_cover` = #{videoCover,jdbcType=VARCHAR},",
          "`review_level` = #{reviewLevel,jdbcType=VARCHAR},",
          "`review_ops_pulp_level` = #{reviewOpsPulpLevel,jdbcType=VARCHAR},",
          "`review_ops_terror_level` = #{reviewOpsTerrorLevel,jdbcType=VARCHAR},",
          "`review_ops_politician_level` = #{reviewOpsPoliticianLevel,jdbcType=VARCHAR},",
          "`review_segments_op` = #{reviewSegmentsOp,jdbcType=VARCHAR},",
          "`review_segments_offsetBegin` = #{reviewSegmentsOffsetbegin,jdbcType=INTEGER},",
          "`review_segments_offsetEnd` = #{reviewSegmentsOffsetend,jdbcType=INTEGER},",
          "`review_segments_uri` = #{reviewSegmentsUri,jdbcType=VARCHAR},",
          "`review_segments_cuts_offset` = #{reviewSegmentsCutsOffset,jdbcType=INTEGER},",
          "`review_segments_cuts_uri` = #{reviewSegmentsCutsUri,jdbcType=VARCHAR},",
          "`review_segments_level` = #{reviewSegmentsLevel,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReviewVideoSegments record);
}