package cn.qiniu.mapper;

import cn.qiniu.entity.ReviewVideoManagerCuts;
import cn.qiniu.entity.ReviewVideoManagerCutsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReviewVideoManagerCutsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    int countByExample(ReviewVideoManagerCutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewVideoManagerCutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `review_video_manager_cuts`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `review_video_manager_cuts` (`id`, `video_id`, ",
        "`segment_id`, `offset`, ",
        "`uri`, `created_by`, ",
        "`created_at`, `updated_by`, ",
        "`updated_at`, `del_flg`)",
        "values (#{id,jdbcType=VARCHAR}, #{videoId,jdbcType=VARCHAR}, ",
        "#{segmentId,jdbcType=VARCHAR}, #{offset,jdbcType=INTEGER}, ",
        "#{uri,jdbcType=VARCHAR}, #{createdBy,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedBy,jdbcType=VARCHAR}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{delFlg,jdbcType=VARCHAR})"
    })
    int insert(ReviewVideoManagerCuts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    int insertSelective(ReviewVideoManagerCuts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    List<ReviewVideoManagerCuts> selectByExample(ReviewVideoManagerCutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `video_id`, `segment_id`, `offset`, `uri`, `created_by`, `created_at`, ",
        "`updated_by`, `updated_at`, `del_flg`",
        "from `review_video_manager_cuts`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReviewVideoManagerCuts selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewVideoManagerCuts record, @Param("example") ReviewVideoManagerCutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewVideoManagerCuts record, @Param("example") ReviewVideoManagerCutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReviewVideoManagerCuts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_cuts
     *
     * @mbggenerated
     */
    @Update({
        "update `review_video_manager_cuts`",
        "set `video_id` = #{videoId,jdbcType=VARCHAR},",
          "`segment_id` = #{segmentId,jdbcType=VARCHAR},",
          "`offset` = #{offset,jdbcType=INTEGER},",
          "`uri` = #{uri,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReviewVideoManagerCuts record);
}