package cn.qiniu.mapper;

import cn.qiniu.entity.ReviewVideoInformation;
import cn.qiniu.entity.ReviewVideoInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReviewVideoInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    int countByExample(ReviewVideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewVideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `review_video_information`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `review_video_information` (`id`, `video_id`, ",
        "`video_uri`, `video_desc`, ",
        "`video_meta`, `stop_review_flg`, ",
        "`wait`, `review_type`, `video_save`, ",
        "`hook_host`, `created_by`, ",
        "`created_at`, `updated_by`, ",
        "`updated_at`, `del_flg`, ",
        "`video_type`)",
        "values (#{id,jdbcType=VARCHAR}, #{videoId,jdbcType=VARCHAR}, ",
        "#{videoUri,jdbcType=VARCHAR}, #{videoDesc,jdbcType=VARCHAR}, ",
        "#{videoMeta,jdbcType=VARCHAR}, #{stopReviewFlg,jdbcType=VARCHAR}, ",
        "#{wait,jdbcType=BIT}, #{reviewType,jdbcType=VARCHAR}, #{videoSave,jdbcType=VARCHAR}, ",
        "#{hookHost,jdbcType=VARCHAR}, #{createdBy,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedBy,jdbcType=VARCHAR}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{delFlg,jdbcType=VARCHAR}, ",
        "#{videoType,jdbcType=VARCHAR})"
    })
    int insert(ReviewVideoInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    int insertSelective(ReviewVideoInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    List<ReviewVideoInformation> selectByExample(ReviewVideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `video_id`, `video_uri`, `video_desc`, `video_meta`, `stop_review_flg`, ",
        "`wait`, `review_type`, `video_save`, `hook_host`, `created_by`, `created_at`, ",
        "`updated_by`, `updated_at`, `del_flg`, `video_type`",
        "from `review_video_information`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReviewVideoInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewVideoInformation record, @Param("example") ReviewVideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewVideoInformation record, @Param("example") ReviewVideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReviewVideoInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_information
     *
     * @mbggenerated
     */
    @Update({
        "update `review_video_information`",
        "set `video_id` = #{videoId,jdbcType=VARCHAR},",
          "`video_uri` = #{videoUri,jdbcType=VARCHAR},",
          "`video_desc` = #{videoDesc,jdbcType=VARCHAR},",
          "`video_meta` = #{videoMeta,jdbcType=VARCHAR},",
          "`stop_review_flg` = #{stopReviewFlg,jdbcType=VARCHAR},",
          "`wait` = #{wait,jdbcType=BIT},",
          "`review_type` = #{reviewType,jdbcType=VARCHAR},",
          "`video_save` = #{videoSave,jdbcType=VARCHAR},",
          "`hook_host` = #{hookHost,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR},",
          "`video_type` = #{videoType,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReviewVideoInformation record);
}