package cn.qiniu.mapper;

import cn.qiniu.entity.ReviewVideoManagerSegments;
import cn.qiniu.entity.ReviewVideoManagerSegmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReviewVideoManagerSegmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    int countByExample(ReviewVideoManagerSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewVideoManagerSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `review_video_manager_segments`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `review_video_manager_segments` (`id`, `video_id`, ",
        "`op`, `offset_begin`, ",
        "`offset_end`, `uri`, ",
        "`level`, `manual_level`, ",
        "`robotic_level`, `robotic_score`, ",
        "`created_by`, `created_at`, ",
        "`updated_by`, `updated_at`, ",
        "`del_flg`)",
        "values (#{id,jdbcType=VARCHAR}, #{videoId,jdbcType=VARCHAR}, ",
        "#{op,jdbcType=VARCHAR}, #{offsetBegin,jdbcType=INTEGER}, ",
        "#{offsetEnd,jdbcType=INTEGER}, #{uri,jdbcType=VARCHAR}, ",
        "#{level,jdbcType=VARCHAR}, #{manualLevel,jdbcType=VARCHAR}, ",
        "#{roboticLevel,jdbcType=VARCHAR}, #{roboticScore,jdbcType=DECIMAL}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedBy,jdbcType=VARCHAR}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{delFlg,jdbcType=VARCHAR})"
    })
    int insert(ReviewVideoManagerSegments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    int insertSelective(ReviewVideoManagerSegments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    List<ReviewVideoManagerSegments> selectByExample(ReviewVideoManagerSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `video_id`, `op`, `offset_begin`, `offset_end`, `uri`, `level`, `manual_level`, ",
        "`robotic_level`, `robotic_score`, `created_by`, `created_at`, `updated_by`, ",
        "`updated_at`, `del_flg`",
        "from `review_video_manager_segments`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReviewVideoManagerSegments selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewVideoManagerSegments record, @Param("example") ReviewVideoManagerSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewVideoManagerSegments record, @Param("example") ReviewVideoManagerSegmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReviewVideoManagerSegments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager_segments
     *
     * @mbggenerated
     */
    @Update({
        "update `review_video_manager_segments`",
        "set `video_id` = #{videoId,jdbcType=VARCHAR},",
          "`op` = #{op,jdbcType=VARCHAR},",
          "`offset_begin` = #{offsetBegin,jdbcType=INTEGER},",
          "`offset_end` = #{offsetEnd,jdbcType=INTEGER},",
          "`uri` = #{uri,jdbcType=VARCHAR},",
          "`level` = #{level,jdbcType=VARCHAR},",
          "`manual_level` = #{manualLevel,jdbcType=VARCHAR},",
          "`robotic_level` = #{roboticLevel,jdbcType=VARCHAR},",
          "`robotic_score` = #{roboticScore,jdbcType=DECIMAL},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReviewVideoManagerSegments record);
}