package cn.qiniu.mapper;

import cn.qiniu.entity.SysUser;
import cn.qiniu.entity.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `sys_user`",
        "where `user_id` = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `sys_user` (`user_id`, `login_nm`, ",
        "`password`, `user_nm`, ",
        "`sex`, `tel_no`, `email`, ",
        "`role_id`, `rmrk`, `del_flg`, ",
        "`created_by`, `created_at`, ",
        "`updated_by`, `updated_at`)",
        "values (#{userId,jdbcType=VARCHAR}, #{loginNm,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{userNm,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=VARCHAR}, #{telNo,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{roleId,jdbcType=VARCHAR}, #{rmrk,jdbcType=VARCHAR}, #{delFlg,jdbcType=VARCHAR}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedBy,jdbcType=VARCHAR}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`user_id`, `login_nm`, `password`, `user_nm`, `sex`, `tel_no`, `email`, `role_id`, ",
        "`rmrk`, `del_flg`, `created_by`, `created_at`, `updated_by`, `updated_at`",
        "from `sys_user`",
        "where `user_id` = #{userId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    SysUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Update({
        "update `sys_user`",
        "set `login_nm` = #{loginNm,jdbcType=VARCHAR},",
          "`password` = #{password,jdbcType=VARCHAR},",
          "`user_nm` = #{userNm,jdbcType=VARCHAR},",
          "`sex` = #{sex,jdbcType=VARCHAR},",
          "`tel_no` = #{telNo,jdbcType=VARCHAR},",
          "`email` = #{email,jdbcType=VARCHAR},",
          "`role_id` = #{roleId,jdbcType=VARCHAR},",
          "`rmrk` = #{rmrk,jdbcType=VARCHAR},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP}",
        "where `user_id` = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysUser record);
}