package cn.qiniu.mapper;

import cn.qiniu.entity.ReviewVideoOps;
import cn.qiniu.entity.ReviewVideoOpsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReviewVideoOpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    int countByExample(ReviewVideoOpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    int deleteByExample(ReviewVideoOpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `review_video_ops`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `review_video_ops` (`id`, `job_id`, ",
        "`video_id`, `op`, `levels`, ",
        "`op_save`, `op_hook_host`, ",
        "`created_by`, `created_at`, ",
        "`updated_by`, `updated_at`, ",
        "`del_flg`)",
        "values (#{id,jdbcType=VARCHAR}, #{jobId,jdbcType=VARCHAR}, ",
        "#{videoId,jdbcType=VARCHAR}, #{op,jdbcType=VARCHAR}, #{levels,jdbcType=VARCHAR}, ",
        "#{opSave,jdbcType=VARCHAR}, #{opHookHost,jdbcType=VARCHAR}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedBy,jdbcType=VARCHAR}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{delFlg,jdbcType=VARCHAR})"
    })
    int insert(ReviewVideoOps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    int insertSelective(ReviewVideoOps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    List<ReviewVideoOps> selectByExample(ReviewVideoOpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `job_id`, `video_id`, `op`, `levels`, `op_save`, `op_hook_host`, `created_by`, ",
        "`created_at`, `updated_by`, `updated_at`, `del_flg`",
        "from `review_video_ops`",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReviewVideoOps selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReviewVideoOps record, @Param("example") ReviewVideoOpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReviewVideoOps record, @Param("example") ReviewVideoOpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReviewVideoOps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_ops
     *
     * @mbggenerated
     */
    @Update({
        "update `review_video_ops`",
        "set `job_id` = #{jobId,jdbcType=VARCHAR},",
          "`video_id` = #{videoId,jdbcType=VARCHAR},",
          "`op` = #{op,jdbcType=VARCHAR},",
          "`levels` = #{levels,jdbcType=VARCHAR},",
          "`op_save` = #{opSave,jdbcType=VARCHAR},",
          "`op_hook_host` = #{opHookHost,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReviewVideoOps record);
}