package cn.qiniu.mapper;

import cn.qiniu.entity.SysRoleResource;
import cn.qiniu.entity.SysRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    int countByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    int deleteByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `sys_role_resource`",
        "where `role_resource_id` = #{roleResourceId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `sys_role_resource` (`role_resource_id`, `role_id`, ",
        "`resource_id`, `del_flg`, ",
        "`created_by`, `created_at`, ",
        "`updated_by`, `updated_at`)",
        "values (#{roleResourceId,jdbcType=VARCHAR}, #{roleId,jdbcType=VARCHAR}, ",
        "#{resourceId,jdbcType=VARCHAR}, #{delFlg,jdbcType=VARCHAR}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedBy,jdbcType=VARCHAR}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    List<SysRoleResource> selectByExample(SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`role_resource_id`, `role_id`, `resource_id`, `del_flg`, `created_by`, `created_at`, ",
        "`updated_by`, `updated_at`",
        "from `sys_role_resource`",
        "where `role_resource_id` = #{roleResourceId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    SysRoleResource selectByPrimaryKey(String roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRoleResource record, @Param("example") SysRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    @Update({
        "update `sys_role_resource`",
        "set `role_id` = #{roleId,jdbcType=VARCHAR},",
          "`resource_id` = #{resourceId,jdbcType=VARCHAR},",
          "`del_flg` = #{delFlg,jdbcType=VARCHAR},",
          "`created_by` = #{createdBy,jdbcType=VARCHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`updated_by` = #{updatedBy,jdbcType=VARCHAR},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP}",
        "where `role_resource_id` = #{roleResourceId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysRoleResource record);
}