package cn.qiniu.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReviewVideoManagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public ReviewVideoManagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("`job_id` is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("`job_id` is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(String value) {
            addCriterion("`job_id` =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(String value) {
            addCriterion("`job_id` <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(String value) {
            addCriterion("`job_id` >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(String value) {
            addCriterion("`job_id` >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(String value) {
            addCriterion("`job_id` <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(String value) {
            addCriterion("`job_id` <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLike(String value) {
            addCriterion("`job_id` like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotLike(String value) {
            addCriterion("`job_id` not like", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<String> values) {
            addCriterion("`job_id` in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<String> values) {
            addCriterion("`job_id` not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(String value1, String value2) {
            addCriterion("`job_id` between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(String value1, String value2) {
            addCriterion("`job_id` not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("`source` is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("`source` is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("`source` =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("`source` <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("`source` >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("`source` >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("`source` <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("`source` <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("`source` like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("`source` not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("`source` in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("`source` not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("`source` between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("`source` not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andVideoUriIsNull() {
            addCriterion("`video_uri` is null");
            return (Criteria) this;
        }

        public Criteria andVideoUriIsNotNull() {
            addCriterion("`video_uri` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUriEqualTo(String value) {
            addCriterion("`video_uri` =", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotEqualTo(String value) {
            addCriterion("`video_uri` <>", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriGreaterThan(String value) {
            addCriterion("`video_uri` >", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriGreaterThanOrEqualTo(String value) {
            addCriterion("`video_uri` >=", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriLessThan(String value) {
            addCriterion("`video_uri` <", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriLessThanOrEqualTo(String value) {
            addCriterion("`video_uri` <=", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriLike(String value) {
            addCriterion("`video_uri` like", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotLike(String value) {
            addCriterion("`video_uri` not like", value, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriIn(List<String> values) {
            addCriterion("`video_uri` in", values, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotIn(List<String> values) {
            addCriterion("`video_uri` not in", values, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriBetween(String value1, String value2) {
            addCriterion("`video_uri` between", value1, value2, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoUriNotBetween(String value1, String value2) {
            addCriterion("`video_uri` not between", value1, value2, "videoUri");
            return (Criteria) this;
        }

        public Criteria andVideoCoverIsNull() {
            addCriterion("`video_cover` is null");
            return (Criteria) this;
        }

        public Criteria andVideoCoverIsNotNull() {
            addCriterion("`video_cover` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCoverEqualTo(String value) {
            addCriterion("`video_cover` =", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotEqualTo(String value) {
            addCriterion("`video_cover` <>", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverGreaterThan(String value) {
            addCriterion("`video_cover` >", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverGreaterThanOrEqualTo(String value) {
            addCriterion("`video_cover` >=", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverLessThan(String value) {
            addCriterion("`video_cover` <", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverLessThanOrEqualTo(String value) {
            addCriterion("`video_cover` <=", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverLike(String value) {
            addCriterion("`video_cover` like", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotLike(String value) {
            addCriterion("`video_cover` not like", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverIn(List<String> values) {
            addCriterion("`video_cover` in", values, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotIn(List<String> values) {
            addCriterion("`video_cover` not in", values, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverBetween(String value1, String value2) {
            addCriterion("`video_cover` between", value1, value2, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotBetween(String value1, String value2) {
            addCriterion("`video_cover` not between", value1, value2, "videoCover");
            return (Criteria) this;
        }

        public Criteria andReviewStageIsNull() {
            addCriterion("`review_stage` is null");
            return (Criteria) this;
        }

        public Criteria andReviewStageIsNotNull() {
            addCriterion("`review_stage` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewStageEqualTo(String value) {
            addCriterion("`review_stage` =", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageNotEqualTo(String value) {
            addCriterion("`review_stage` <>", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageGreaterThan(String value) {
            addCriterion("`review_stage` >", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageGreaterThanOrEqualTo(String value) {
            addCriterion("`review_stage` >=", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageLessThan(String value) {
            addCriterion("`review_stage` <", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageLessThanOrEqualTo(String value) {
            addCriterion("`review_stage` <=", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageLike(String value) {
            addCriterion("`review_stage` like", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageNotLike(String value) {
            addCriterion("`review_stage` not like", value, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageIn(List<String> values) {
            addCriterion("`review_stage` in", values, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageNotIn(List<String> values) {
            addCriterion("`review_stage` not in", values, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageBetween(String value1, String value2) {
            addCriterion("`review_stage` between", value1, value2, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewStageNotBetween(String value1, String value2) {
            addCriterion("`review_stage` not between", value1, value2, "reviewStage");
            return (Criteria) this;
        }

        public Criteria andReviewLevelIsNull() {
            addCriterion("`review_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewLevelIsNotNull() {
            addCriterion("`review_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewLevelEqualTo(String value) {
            addCriterion("`review_level` =", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelNotEqualTo(String value) {
            addCriterion("`review_level` <>", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelGreaterThan(String value) {
            addCriterion("`review_level` >", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_level` >=", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelLessThan(String value) {
            addCriterion("`review_level` <", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_level` <=", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelLike(String value) {
            addCriterion("`review_level` like", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelNotLike(String value) {
            addCriterion("`review_level` not like", value, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelIn(List<String> values) {
            addCriterion("`review_level` in", values, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelNotIn(List<String> values) {
            addCriterion("`review_level` not in", values, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelBetween(String value1, String value2) {
            addCriterion("`review_level` between", value1, value2, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewLevelNotBetween(String value1, String value2) {
            addCriterion("`review_level` not between", value1, value2, "reviewLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelIsNull() {
            addCriterion("`review_manual_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelIsNotNull() {
            addCriterion("`review_manual_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelEqualTo(String value) {
            addCriterion("`review_manual_level` =", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelNotEqualTo(String value) {
            addCriterion("`review_manual_level` <>", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelGreaterThan(String value) {
            addCriterion("`review_manual_level` >", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_manual_level` >=", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelLessThan(String value) {
            addCriterion("`review_manual_level` <", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_manual_level` <=", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelLike(String value) {
            addCriterion("`review_manual_level` like", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelNotLike(String value) {
            addCriterion("`review_manual_level` not like", value, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelIn(List<String> values) {
            addCriterion("`review_manual_level` in", values, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelNotIn(List<String> values) {
            addCriterion("`review_manual_level` not in", values, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelBetween(String value1, String value2) {
            addCriterion("`review_manual_level` between", value1, value2, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewManualLevelNotBetween(String value1, String value2) {
            addCriterion("`review_manual_level` not between", value1, value2, "reviewManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelIsNull() {
            addCriterion("`review_robotic_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelIsNotNull() {
            addCriterion("`review_robotic_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelEqualTo(String value) {
            addCriterion("`review_robotic_level` =", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelNotEqualTo(String value) {
            addCriterion("`review_robotic_level` <>", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelGreaterThan(String value) {
            addCriterion("`review_robotic_level` >", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_robotic_level` >=", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelLessThan(String value) {
            addCriterion("`review_robotic_level` <", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_robotic_level` <=", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelLike(String value) {
            addCriterion("`review_robotic_level` like", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelNotLike(String value) {
            addCriterion("`review_robotic_level` not like", value, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelIn(List<String> values) {
            addCriterion("`review_robotic_level` in", values, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelNotIn(List<String> values) {
            addCriterion("`review_robotic_level` not in", values, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelBetween(String value1, String value2) {
            addCriterion("`review_robotic_level` between", value1, value2, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticLevelNotBetween(String value1, String value2) {
            addCriterion("`review_robotic_level` not between", value1, value2, "reviewRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreIsNull() {
            addCriterion("`review_robotic_score` is null");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreIsNotNull() {
            addCriterion("`review_robotic_score` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreEqualTo(BigDecimal value) {
            addCriterion("`review_robotic_score` =", value, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreNotEqualTo(BigDecimal value) {
            addCriterion("`review_robotic_score` <>", value, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreGreaterThan(BigDecimal value) {
            addCriterion("`review_robotic_score` >", value, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_robotic_score` >=", value, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreLessThan(BigDecimal value) {
            addCriterion("`review_robotic_score` <", value, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_robotic_score` <=", value, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreIn(List<BigDecimal> values) {
            addCriterion("`review_robotic_score` in", values, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreNotIn(List<BigDecimal> values) {
            addCriterion("`review_robotic_score` not in", values, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_robotic_score` between", value1, value2, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewRoboticScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_robotic_score` not between", value1, value2, "reviewRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelIsNull() {
            addCriterion("`review_ops_pulp_manual_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelIsNotNull() {
            addCriterion("`review_ops_pulp_manual_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelEqualTo(String value) {
            addCriterion("`review_ops_pulp_manual_level` =", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelNotEqualTo(String value) {
            addCriterion("`review_ops_pulp_manual_level` <>", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelGreaterThan(String value) {
            addCriterion("`review_ops_pulp_manual_level` >", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_ops_pulp_manual_level` >=", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelLessThan(String value) {
            addCriterion("`review_ops_pulp_manual_level` <", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_ops_pulp_manual_level` <=", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelLike(String value) {
            addCriterion("`review_ops_pulp_manual_level` like", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelNotLike(String value) {
            addCriterion("`review_ops_pulp_manual_level` not like", value, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelIn(List<String> values) {
            addCriterion("`review_ops_pulp_manual_level` in", values, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelNotIn(List<String> values) {
            addCriterion("`review_ops_pulp_manual_level` not in", values, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelBetween(String value1, String value2) {
            addCriterion("`review_ops_pulp_manual_level` between", value1, value2, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpManualLevelNotBetween(String value1, String value2) {
            addCriterion("`review_ops_pulp_manual_level` not between", value1, value2, "reviewOpsPulpManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelIsNull() {
            addCriterion("`review_ops_pulp_robotic_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelIsNotNull() {
            addCriterion("`review_ops_pulp_robotic_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelEqualTo(String value) {
            addCriterion("`review_ops_pulp_robotic_level` =", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelNotEqualTo(String value) {
            addCriterion("`review_ops_pulp_robotic_level` <>", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelGreaterThan(String value) {
            addCriterion("`review_ops_pulp_robotic_level` >", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_ops_pulp_robotic_level` >=", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelLessThan(String value) {
            addCriterion("`review_ops_pulp_robotic_level` <", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_ops_pulp_robotic_level` <=", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelLike(String value) {
            addCriterion("`review_ops_pulp_robotic_level` like", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelNotLike(String value) {
            addCriterion("`review_ops_pulp_robotic_level` not like", value, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelIn(List<String> values) {
            addCriterion("`review_ops_pulp_robotic_level` in", values, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelNotIn(List<String> values) {
            addCriterion("`review_ops_pulp_robotic_level` not in", values, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelBetween(String value1, String value2) {
            addCriterion("`review_ops_pulp_robotic_level` between", value1, value2, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticLevelNotBetween(String value1, String value2) {
            addCriterion("`review_ops_pulp_robotic_level` not between", value1, value2, "reviewOpsPulpRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreIsNull() {
            addCriterion("`review_ops_pulp_robotic_score` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreIsNotNull() {
            addCriterion("`review_ops_pulp_robotic_score` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreEqualTo(BigDecimal value) {
            addCriterion("`review_ops_pulp_robotic_score` =", value, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreNotEqualTo(BigDecimal value) {
            addCriterion("`review_ops_pulp_robotic_score` <>", value, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreGreaterThan(BigDecimal value) {
            addCriterion("`review_ops_pulp_robotic_score` >", value, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_ops_pulp_robotic_score` >=", value, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreLessThan(BigDecimal value) {
            addCriterion("`review_ops_pulp_robotic_score` <", value, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_ops_pulp_robotic_score` <=", value, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreIn(List<BigDecimal> values) {
            addCriterion("`review_ops_pulp_robotic_score` in", values, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreNotIn(List<BigDecimal> values) {
            addCriterion("`review_ops_pulp_robotic_score` not in", values, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_ops_pulp_robotic_score` between", value1, value2, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPulpRoboticScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_ops_pulp_robotic_score` not between", value1, value2, "reviewOpsPulpRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelIsNull() {
            addCriterion("`review_ops_terror_manual_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelIsNotNull() {
            addCriterion("`review_ops_terror_manual_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelEqualTo(String value) {
            addCriterion("`review_ops_terror_manual_level` =", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelNotEqualTo(String value) {
            addCriterion("`review_ops_terror_manual_level` <>", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelGreaterThan(String value) {
            addCriterion("`review_ops_terror_manual_level` >", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_ops_terror_manual_level` >=", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelLessThan(String value) {
            addCriterion("`review_ops_terror_manual_level` <", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_ops_terror_manual_level` <=", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelLike(String value) {
            addCriterion("`review_ops_terror_manual_level` like", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelNotLike(String value) {
            addCriterion("`review_ops_terror_manual_level` not like", value, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelIn(List<String> values) {
            addCriterion("`review_ops_terror_manual_level` in", values, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelNotIn(List<String> values) {
            addCriterion("`review_ops_terror_manual_level` not in", values, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelBetween(String value1, String value2) {
            addCriterion("`review_ops_terror_manual_level` between", value1, value2, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorManualLevelNotBetween(String value1, String value2) {
            addCriterion("`review_ops_terror_manual_level` not between", value1, value2, "reviewOpsTerrorManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelIsNull() {
            addCriterion("`review_ops_terror_robotic_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelIsNotNull() {
            addCriterion("`review_ops_terror_robotic_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelEqualTo(String value) {
            addCriterion("`review_ops_terror_robotic_level` =", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelNotEqualTo(String value) {
            addCriterion("`review_ops_terror_robotic_level` <>", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelGreaterThan(String value) {
            addCriterion("`review_ops_terror_robotic_level` >", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_ops_terror_robotic_level` >=", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelLessThan(String value) {
            addCriterion("`review_ops_terror_robotic_level` <", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_ops_terror_robotic_level` <=", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelLike(String value) {
            addCriterion("`review_ops_terror_robotic_level` like", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelNotLike(String value) {
            addCriterion("`review_ops_terror_robotic_level` not like", value, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelIn(List<String> values) {
            addCriterion("`review_ops_terror_robotic_level` in", values, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelNotIn(List<String> values) {
            addCriterion("`review_ops_terror_robotic_level` not in", values, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelBetween(String value1, String value2) {
            addCriterion("`review_ops_terror_robotic_level` between", value1, value2, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticLevelNotBetween(String value1, String value2) {
            addCriterion("`review_ops_terror_robotic_level` not between", value1, value2, "reviewOpsTerrorRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreIsNull() {
            addCriterion("`review_ops_terror_robotic_score` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreIsNotNull() {
            addCriterion("`review_ops_terror_robotic_score` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreEqualTo(BigDecimal value) {
            addCriterion("`review_ops_terror_robotic_score` =", value, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreNotEqualTo(BigDecimal value) {
            addCriterion("`review_ops_terror_robotic_score` <>", value, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreGreaterThan(BigDecimal value) {
            addCriterion("`review_ops_terror_robotic_score` >", value, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_ops_terror_robotic_score` >=", value, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreLessThan(BigDecimal value) {
            addCriterion("`review_ops_terror_robotic_score` <", value, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_ops_terror_robotic_score` <=", value, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreIn(List<BigDecimal> values) {
            addCriterion("`review_ops_terror_robotic_score` in", values, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreNotIn(List<BigDecimal> values) {
            addCriterion("`review_ops_terror_robotic_score` not in", values, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_ops_terror_robotic_score` between", value1, value2, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsTerrorRoboticScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_ops_terror_robotic_score` not between", value1, value2, "reviewOpsTerrorRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelIsNull() {
            addCriterion("`review_ops_politician_manual_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelIsNotNull() {
            addCriterion("`review_ops_politician_manual_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelEqualTo(String value) {
            addCriterion("`review_ops_politician_manual_level` =", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelNotEqualTo(String value) {
            addCriterion("`review_ops_politician_manual_level` <>", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelGreaterThan(String value) {
            addCriterion("`review_ops_politician_manual_level` >", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_ops_politician_manual_level` >=", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelLessThan(String value) {
            addCriterion("`review_ops_politician_manual_level` <", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_ops_politician_manual_level` <=", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelLike(String value) {
            addCriterion("`review_ops_politician_manual_level` like", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelNotLike(String value) {
            addCriterion("`review_ops_politician_manual_level` not like", value, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelIn(List<String> values) {
            addCriterion("`review_ops_politician_manual_level` in", values, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelNotIn(List<String> values) {
            addCriterion("`review_ops_politician_manual_level` not in", values, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelBetween(String value1, String value2) {
            addCriterion("`review_ops_politician_manual_level` between", value1, value2, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianManualLevelNotBetween(String value1, String value2) {
            addCriterion("`review_ops_politician_manual_level` not between", value1, value2, "reviewOpsPoliticianManualLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelIsNull() {
            addCriterion("`review_ops_politician_robotic_level` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelIsNotNull() {
            addCriterion("`review_ops_politician_robotic_level` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelEqualTo(String value) {
            addCriterion("`review_ops_politician_robotic_level` =", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelNotEqualTo(String value) {
            addCriterion("`review_ops_politician_robotic_level` <>", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelGreaterThan(String value) {
            addCriterion("`review_ops_politician_robotic_level` >", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`review_ops_politician_robotic_level` >=", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelLessThan(String value) {
            addCriterion("`review_ops_politician_robotic_level` <", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelLessThanOrEqualTo(String value) {
            addCriterion("`review_ops_politician_robotic_level` <=", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelLike(String value) {
            addCriterion("`review_ops_politician_robotic_level` like", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelNotLike(String value) {
            addCriterion("`review_ops_politician_robotic_level` not like", value, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelIn(List<String> values) {
            addCriterion("`review_ops_politician_robotic_level` in", values, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelNotIn(List<String> values) {
            addCriterion("`review_ops_politician_robotic_level` not in", values, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelBetween(String value1, String value2) {
            addCriterion("`review_ops_politician_robotic_level` between", value1, value2, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticLevelNotBetween(String value1, String value2) {
            addCriterion("`review_ops_politician_robotic_level` not between", value1, value2, "reviewOpsPoliticianRoboticLevel");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreIsNull() {
            addCriterion("`review_ops_politician_robotic_score` is null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreIsNotNull() {
            addCriterion("`review_ops_politician_robotic_score` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreEqualTo(BigDecimal value) {
            addCriterion("`review_ops_politician_robotic_score` =", value, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreNotEqualTo(BigDecimal value) {
            addCriterion("`review_ops_politician_robotic_score` <>", value, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreGreaterThan(BigDecimal value) {
            addCriterion("`review_ops_politician_robotic_score` >", value, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_ops_politician_robotic_score` >=", value, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreLessThan(BigDecimal value) {
            addCriterion("`review_ops_politician_robotic_score` <", value, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`review_ops_politician_robotic_score` <=", value, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreIn(List<BigDecimal> values) {
            addCriterion("`review_ops_politician_robotic_score` in", values, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreNotIn(List<BigDecimal> values) {
            addCriterion("`review_ops_politician_robotic_score` not in", values, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_ops_politician_robotic_score` between", value1, value2, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andReviewOpsPoliticianRoboticScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`review_ops_politician_robotic_score` not between", value1, value2, "reviewOpsPoliticianRoboticScore");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNull() {
            addCriterion("`video_name` is null");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNotNull() {
            addCriterion("`video_name` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNameEqualTo(String value) {
            addCriterion("`video_name` =", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotEqualTo(String value) {
            addCriterion("`video_name` <>", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThan(String value) {
            addCriterion("`video_name` >", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThanOrEqualTo(String value) {
            addCriterion("`video_name` >=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThan(String value) {
            addCriterion("`video_name` <", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThanOrEqualTo(String value) {
            addCriterion("`video_name` <=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLike(String value) {
            addCriterion("`video_name` like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotLike(String value) {
            addCriterion("`video_name` not like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameIn(List<String> values) {
            addCriterion("`video_name` in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotIn(List<String> values) {
            addCriterion("`video_name` not in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameBetween(String value1, String value2) {
            addCriterion("`video_name` between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotBetween(String value1, String value2) {
            addCriterion("`video_name` not between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNull() {
            addCriterion("`video_time` is null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNotNull() {
            addCriterion("`video_time` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeEqualTo(String value) {
            addCriterion("`video_time` =", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotEqualTo(String value) {
            addCriterion("`video_time` <>", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThan(String value) {
            addCriterion("`video_time` >", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThanOrEqualTo(String value) {
            addCriterion("`video_time` >=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThan(String value) {
            addCriterion("`video_time` <", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThanOrEqualTo(String value) {
            addCriterion("`video_time` <=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLike(String value) {
            addCriterion("`video_time` like", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotLike(String value) {
            addCriterion("`video_time` not like", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIn(List<String> values) {
            addCriterion("`video_time` in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotIn(List<String> values) {
            addCriterion("`video_time` not in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeBetween(String value1, String value2) {
            addCriterion("`video_time` between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotBetween(String value1, String value2) {
            addCriterion("`video_time` not between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andReviewerIdIsNull() {
            addCriterion("`reviewer_id` is null");
            return (Criteria) this;
        }

        public Criteria andReviewerIdIsNotNull() {
            addCriterion("`reviewer_id` is not null");
            return (Criteria) this;
        }

        public Criteria andReviewerIdEqualTo(String value) {
            addCriterion("`reviewer_id` =", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotEqualTo(String value) {
            addCriterion("`reviewer_id` <>", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdGreaterThan(String value) {
            addCriterion("`reviewer_id` >", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdGreaterThanOrEqualTo(String value) {
            addCriterion("`reviewer_id` >=", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdLessThan(String value) {
            addCriterion("`reviewer_id` <", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdLessThanOrEqualTo(String value) {
            addCriterion("`reviewer_id` <=", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdLike(String value) {
            addCriterion("`reviewer_id` like", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotLike(String value) {
            addCriterion("`reviewer_id` not like", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdIn(List<String> values) {
            addCriterion("`reviewer_id` in", values, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotIn(List<String> values) {
            addCriterion("`reviewer_id` not in", values, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdBetween(String value1, String value2) {
            addCriterion("`reviewer_id` between", value1, value2, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotBetween(String value1, String value2) {
            addCriterion("`reviewer_id` not between", value1, value2, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("`created_by` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("`created_by` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("`created_by` =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("`created_by` <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("`created_by` >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("`created_by` >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("`created_by` <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("`created_by` <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("`created_by` like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("`created_by` not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("`created_by` in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("`created_by` not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("`created_by` between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("`created_by` not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("`created_at` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("`created_at` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("`created_at` =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("`created_at` <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("`created_at` >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_at` >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("`created_at` <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`created_at` <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("`created_at` in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("`created_at` not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("`created_at` between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`created_at` not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("`updated_by` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("`updated_by` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("`updated_by` =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("`updated_by` <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("`updated_by` >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("`updated_by` >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("`updated_by` <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("`updated_by` <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("`updated_by` like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("`updated_by` not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("`updated_by` in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("`updated_by` not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("`updated_by` between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("`updated_by` not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("`updated_at` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("`updated_at` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("`updated_at` =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("`updated_at` <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("`updated_at` >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_at` >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("`updated_at` <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`updated_at` <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("`updated_at` in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("`updated_at` not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("`updated_at` between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`updated_at` not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDelFlgIsNull() {
            addCriterion("`del_flg` is null");
            return (Criteria) this;
        }

        public Criteria andDelFlgIsNotNull() {
            addCriterion("`del_flg` is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlgEqualTo(String value) {
            addCriterion("`del_flg` =", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotEqualTo(String value) {
            addCriterion("`del_flg` <>", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgGreaterThan(String value) {
            addCriterion("`del_flg` >", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("`del_flg` >=", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLessThan(String value) {
            addCriterion("`del_flg` <", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLessThanOrEqualTo(String value) {
            addCriterion("`del_flg` <=", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgLike(String value) {
            addCriterion("`del_flg` like", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotLike(String value) {
            addCriterion("`del_flg` not like", value, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgIn(List<String> values) {
            addCriterion("`del_flg` in", values, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotIn(List<String> values) {
            addCriterion("`del_flg` not in", values, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgBetween(String value1, String value2) {
            addCriterion("`del_flg` between", value1, value2, "delFlg");
            return (Criteria) this;
        }

        public Criteria andDelFlgNotBetween(String value1, String value2) {
            addCriterion("`del_flg` not between", value1, value2, "delFlg");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNull() {
            addCriterion("`video_type` is null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNotNull() {
            addCriterion("`video_type` is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeEqualTo(String value) {
            addCriterion("`video_type` =", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotEqualTo(String value) {
            addCriterion("`video_type` <>", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThan(String value) {
            addCriterion("`video_type` >", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`video_type` >=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThan(String value) {
            addCriterion("`video_type` <", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThanOrEqualTo(String value) {
            addCriterion("`video_type` <=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLike(String value) {
            addCriterion("`video_type` like", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotLike(String value) {
            addCriterion("`video_type` not like", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIn(List<String> values) {
            addCriterion("`video_type` in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotIn(List<String> values) {
            addCriterion("`video_type` not in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeBetween(String value1, String value2) {
            addCriterion("`video_type` between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotBetween(String value1, String value2) {
            addCriterion("`video_type` not between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andLiveEndIsNull() {
            addCriterion("`live_end` is null");
            return (Criteria) this;
        }

        public Criteria andLiveEndIsNotNull() {
            addCriterion("`live_end` is not null");
            return (Criteria) this;
        }

        public Criteria andLiveEndEqualTo(String value) {
            addCriterion("`live_end` =", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndNotEqualTo(String value) {
            addCriterion("`live_end` <>", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndGreaterThan(String value) {
            addCriterion("`live_end` >", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndGreaterThanOrEqualTo(String value) {
            addCriterion("`live_end` >=", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndLessThan(String value) {
            addCriterion("`live_end` <", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndLessThanOrEqualTo(String value) {
            addCriterion("`live_end` <=", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndLike(String value) {
            addCriterion("`live_end` like", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndNotLike(String value) {
            addCriterion("`live_end` not like", value, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndIn(List<String> values) {
            addCriterion("`live_end` in", values, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndNotIn(List<String> values) {
            addCriterion("`live_end` not in", values, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndBetween(String value1, String value2) {
            addCriterion("`live_end` between", value1, value2, "liveEnd");
            return (Criteria) this;
        }

        public Criteria andLiveEndNotBetween(String value1, String value2) {
            addCriterion("`live_end` not between", value1, value2, "liveEnd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_manager
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review_video_manager
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}