package cn.qiniu.entity;

import java.util.Date;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_id
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_nm
     *
     * @mbggenerated
     */
    private String resourceNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_type
     *
     * @mbggenerated
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_ident
     *
     * @mbggenerated
     */
    private String resourceIdent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_url
     *
     * @mbggenerated
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.is_show
     *
     * @mbggenerated
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_pic
     *
     * @mbggenerated
     */
    private String resourcePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.sort_no
     *
     * @mbggenerated
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_resource_id
     *
     * @mbggenerated
     */
    private String parentResourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.rmrk
     *
     * @mbggenerated
     */
    private String rmrk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.del_flg
     *
     * @mbggenerated
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated
     */
    public SysResource(String resourceId, String resourceNm, String resourceType, String resourceIdent, String resourceUrl, String isShow, String resourcePic, Integer sortNo, String parentResourceId, String rmrk, String delFlg, String createdBy, Date createdAt, String updatedBy, Date updatedAt) {
        this.resourceId = resourceId;
        this.resourceNm = resourceNm;
        this.resourceType = resourceType;
        this.resourceIdent = resourceIdent;
        this.resourceUrl = resourceUrl;
        this.isShow = isShow;
        this.resourcePic = resourcePic;
        this.sortNo = sortNo;
        this.parentResourceId = parentResourceId;
        this.rmrk = rmrk;
        this.delFlg = delFlg;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated
     */
    public SysResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_id
     *
     * @return the value of sys_resource.resource_id
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_id
     *
     * @param resourceId the value for sys_resource.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_nm
     *
     * @return the value of sys_resource.resource_nm
     *
     * @mbggenerated
     */
    public String getResourceNm() {
        return resourceNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_nm
     *
     * @param resourceNm the value for sys_resource.resource_nm
     *
     * @mbggenerated
     */
    public void setResourceNm(String resourceNm) {
        this.resourceNm = resourceNm == null ? null : resourceNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_type
     *
     * @return the value of sys_resource.resource_type
     *
     * @mbggenerated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_type
     *
     * @param resourceType the value for sys_resource.resource_type
     *
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_ident
     *
     * @return the value of sys_resource.resource_ident
     *
     * @mbggenerated
     */
    public String getResourceIdent() {
        return resourceIdent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_ident
     *
     * @param resourceIdent the value for sys_resource.resource_ident
     *
     * @mbggenerated
     */
    public void setResourceIdent(String resourceIdent) {
        this.resourceIdent = resourceIdent == null ? null : resourceIdent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_url
     *
     * @return the value of sys_resource.resource_url
     *
     * @mbggenerated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_url
     *
     * @param resourceUrl the value for sys_resource.resource_url
     *
     * @mbggenerated
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.is_show
     *
     * @return the value of sys_resource.is_show
     *
     * @mbggenerated
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.is_show
     *
     * @param isShow the value for sys_resource.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_pic
     *
     * @return the value of sys_resource.resource_pic
     *
     * @mbggenerated
     */
    public String getResourcePic() {
        return resourcePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_pic
     *
     * @param resourcePic the value for sys_resource.resource_pic
     *
     * @mbggenerated
     */
    public void setResourcePic(String resourcePic) {
        this.resourcePic = resourcePic == null ? null : resourcePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.sort_no
     *
     * @return the value of sys_resource.sort_no
     *
     * @mbggenerated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.sort_no
     *
     * @param sortNo the value for sys_resource.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_resource_id
     *
     * @return the value of sys_resource.parent_resource_id
     *
     * @mbggenerated
     */
    public String getParentResourceId() {
        return parentResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_resource_id
     *
     * @param parentResourceId the value for sys_resource.parent_resource_id
     *
     * @mbggenerated
     */
    public void setParentResourceId(String parentResourceId) {
        this.parentResourceId = parentResourceId == null ? null : parentResourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.rmrk
     *
     * @return the value of sys_resource.rmrk
     *
     * @mbggenerated
     */
    public String getRmrk() {
        return rmrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.rmrk
     *
     * @param rmrk the value for sys_resource.rmrk
     *
     * @mbggenerated
     */
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk == null ? null : rmrk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.del_flg
     *
     * @return the value of sys_resource.del_flg
     *
     * @mbggenerated
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.del_flg
     *
     * @param delFlg the value for sys_resource.del_flg
     *
     * @mbggenerated
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.created_by
     *
     * @return the value of sys_resource.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.created_by
     *
     * @param createdBy the value for sys_resource.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.created_at
     *
     * @return the value of sys_resource.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.created_at
     *
     * @param createdAt the value for sys_resource.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.updated_by
     *
     * @return the value of sys_resource.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.updated_by
     *
     * @param updatedBy the value for sys_resource.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.updated_at
     *
     * @return the value of sys_resource.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.updated_at
     *
     * @param updatedAt the value for sys_resource.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}