package cn.qiniu.entity;

import java.util.Date;

public class SysRoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.role_resource_id
     *
     * @mbggenerated
     */
    private String roleResourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.resource_id
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.del_flg
     *
     * @mbggenerated
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    public SysRoleResource(String roleResourceId, String roleId, String resourceId, String delFlg, String createdBy, Date createdAt, String updatedBy, Date updatedAt) {
        this.roleResourceId = roleResourceId;
        this.roleId = roleId;
        this.resourceId = resourceId;
        this.delFlg = delFlg;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource
     *
     * @mbggenerated
     */
    public SysRoleResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.role_resource_id
     *
     * @return the value of sys_role_resource.role_resource_id
     *
     * @mbggenerated
     */
    public String getRoleResourceId() {
        return roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.role_resource_id
     *
     * @param roleResourceId the value for sys_role_resource.role_resource_id
     *
     * @mbggenerated
     */
    public void setRoleResourceId(String roleResourceId) {
        this.roleResourceId = roleResourceId == null ? null : roleResourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.role_id
     *
     * @return the value of sys_role_resource.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.role_id
     *
     * @param roleId the value for sys_role_resource.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.resource_id
     *
     * @return the value of sys_role_resource.resource_id
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.resource_id
     *
     * @param resourceId the value for sys_role_resource.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.del_flg
     *
     * @return the value of sys_role_resource.del_flg
     *
     * @mbggenerated
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.del_flg
     *
     * @param delFlg the value for sys_role_resource.del_flg
     *
     * @mbggenerated
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.created_by
     *
     * @return the value of sys_role_resource.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.created_by
     *
     * @param createdBy the value for sys_role_resource.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.created_at
     *
     * @return the value of sys_role_resource.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.created_at
     *
     * @param createdAt the value for sys_role_resource.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.updated_by
     *
     * @return the value of sys_role_resource.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.updated_by
     *
     * @param updatedBy the value for sys_role_resource.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.updated_at
     *
     * @return the value of sys_role_resource.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.updated_at
     *
     * @param updatedAt the value for sys_role_resource.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}